before: { hooks: [ go mod download ] }
builds:
  - goos: [ linux, darwin, windows ]
    goarch: [ amd64, arm ]
    goarm: [ "7" ]
    env: [ CGO_ENABLED=0 ]
    ldflags: |
      -s
      -w
      -X github.com/uhlig-it/plaintoot/plaintoot.version={{.Version}}
      -X github.com/uhlig-it/plaintoot/plaintoot.commit={{.Commit}}
      -X github.com/uhlig-it/plaintoot/plaintoot.date={{.Date}}
checksum: { name_template: "checksums.txt" }
snapshot: { name_template: "{{ .Tag }}-next" }
release:
  name_template: "{{.ProjectName}} release v{{.Version}}"
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "README"
publishers:
  - name: save-release-url
    cmd: sh -c "echo '{{ .ReleaseURL }}' > dist/release-url.txt"
